### ISSUE TITLE
/etc/kargo permission denied

### ISSUE THREAD

**Issue by rbenzair** [kubespray/kargo-cli#23]
Hi,
I try to install kargo in MAC machine with  "pip3 install kargo", i had error.

 running install_data
    creating /etc/kargo
    error: could not create '/etc/kargo': Permission denied

the full error stack 
Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -c "import setuptools, tokenize;**file**='/private/var/folders/fc/8bfsm52550z8jtt578rv7nr40000gn/T/pip-build-inyb0656/kargo/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/fc/8bfsm52550z8jtt578rv7nr40000gn/T/pip-6e5a85bp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/fc/8bfsm52550z8jtt578rv7nr40000gn/T/pip-build-inyb0656/kargo

**Comment by ant31** [comment]
Hi, 

Kargo is compatible with python2 only: 
`pip2 install kargo`

Have tried with root/sudo access?

**Comment by Sispheor** [comment]
+1. After installing via Pip.

```
-bash: /bin/kargo: Permission denied
[root@kargo_vm ~]# ll /bin/kargo
-rw-r--r--. 1 root root 14504 May 15 09:10 /bin/kargo
```

I've had to [chmod +x](url) the binary.

**Comment by Smana** [comment]
it's now deployed in user's home directory
