### ISSUE TITLE
Bare Metal prepare - Issue in inventory generation

### ISSUE THREAD

**Issue by donchh** [kubespray/kargo-cli#48]
When you prepare the inventory for bare metal k8s installation, inventory.cfg isn't well formated 

Running

>  kargo prepare -p ~/kargo_dmprod/ --nodes "k8s-01[ansible_ssh_host=10.190.26.110] k8s-02[ansible_ssh_host=10.190.26.111] k8s-03[ansible_ssh_host=10.190.26.112] k8s-04[ansible_ssh_host=10.190.26.113]"

Result in inventory.cfg : 

> [kube-master]
> k8s-01
> 
> [all]
> k8s-01[ansible_ssh_host=10.190.26.110] k8s-02[ansible_ssh_host=10.190.26.111] k8s-03[ansible_ssh_host=10.190.26.112] k8s-04	ansible_ssh_host=10.190.26.113
> 
> [k8s-cluster:children]
> kube-node
> kube-master
> 
> [kube-node]
> k8s-01[ansible_ssh_host=10.190.26.110] k8s-02[ansible_ssh_host=10.190.26.111] k8s-03[ansible_ssh_host=10.190.26.112] k8s-04
> 
> [etcd]
> k8s-01

**Comment by Smana** [comment]
Hi @donchh Just remove the quotes

**Comment by Smana** [comment]
`kargo prepare -p ~/kargo_dmprod/ --nodes k8s-01[ansible_ssh_host=10.190.26.110] k8s-02[ansible_ssh_host=10.190.26.111] k8s-03[ansible_ssh_host=10.190.26.112] k8s-04[ansible_ssh_host=10.190.26.113]`

**Comment by donchh** [comment]
Hi @Smana  

Well, i need to escape all the bracket. Borring, but ok :)
