### ISSUE TITLE
ubuntu 16.04 as target is not working

### ISSUE THREAD

**Issue by jalbstmeijer** [kubespray/kargo-cli#78]
the official ubuntu 16.0.4 ami does not ship python2 

k8s-charley-7b46c | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "", 
    "module_stdout": "sudo: unable to resolve host ip-10-1-11-186\r\n/bin/sh: 1: /usr/bin/python: not found\r\n", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}

**Comment by ant31** [comment]
you need to use the variable: `bootstrap_os: ubuntu` in your group_vars/all.yml

**Comment by Smana** [comment]
fixed
