### ISSUE TITLE
No file /etc/kargo/kargo.yml in image quay.io/smana/k8s-kargocli:latest

### ISSUE THREAD

**Issue by stamak** [kubespray/kargo-cli#80]
No file /etc/kargo/kargo.yml in container  from quay.io/smana/k8s-kargocli:latest
https://github.com/kubespray/kargo-cli/blob/master/README.md#docker-image

**Comment by nikos9742** [comment]
you need to create that file ;) using the example given

**Comment by Sispheor** [comment]
The file should not be created by the [setup.py](https://github.com/kubespray/kargo-cli/blob/master/setup.py#L30)?

**Comment by Smana** [comment]
now deployed in user's home directory
